# Configuration file.
# You can add any fields you need, be sure to update DropTokenConfiguration accordingly.
template: some-crazy text

logging:
  level: INFO
  appenders:
    - type: console
      threshold: TRACE
      target: stderr

database:
  driverClass: org.h2.Driver
  user: sa
  #  password:
  url: jdbc:h2:./localdb
  maxWaitForConnection: 1s
  validationQuery: "/* MyService Health Check */ SELECT 1"
  minSize: 8
  maxSize: 32
  checkConnectionWhileIdle: false
  evictionInterval: 10s
  minIdleTime: 1 minute
  properties:
    charSet: UTF-8
    hibernate.dialect: org.hibernate.dialect.H2Dialect
    hibernate.show_sql: true
    hibernate.generate_statistics: false
    hibernate.hbm2ddl.auto: validate
    # hibernate.id.new_generator_mappings: false
